### ISSUE TITLE
Compiling using mkl

### ISSUE THREAD

**Issue by hherbol** [potfit/potfit#17]
So, when compiling with MKL I find that there's a library issue in the Makefile.inc that can be fixed if every line that looks like so:

    CINCLUDE      += -I${MKLDIR}/include`
    LIBS          += -Wl,--start-group -lmkl_intel_lp64 -lmkl_sequential \
                   -lmkl_core -Wl,--end-group -lpthread

Instead were:

    CINCLUDE      += -I${MKLDIR}/include
    LIBS          += -L${MKLDIR}/lib/intel64
    LIBS          += -Wl,--start-group -lmkl_intel_lp64 -lmkl_sequential \
                   -lmkl_core -Wl,--end-group -lpthread

Essentially, the make cannot find the mkl libraries/includes.  This could in theory just be user error (that being the libraries weren't installed properly on the user's side), but it's an easy fix that makes installation more robust and error-free.

Henry

**Comment by dschopf** [comment]
Maybe this will help some people, but I would highly recommend using the
script provided by MKL to properly set your environment variables.

For me it is located in /opt/intel/bin/iccvars.sh and I have put
`source /opt/intel/bin/iccvars.sh -arch intel64`
in my .bashrc file.

It adjusts my LD_LIBRARY_PATH to include
`/opt/intel/compilers_and_libraries_2016.1.150/linux/compiler/lib/intel64`,
which is what you are trying to add manually to the Makefile.
