### ISSUE TITLE
Potential file - CRLF on last line

### ISSUE THREAD

**Issue by p-bro** [potfit/potfit#28]
Not sure if that's a bug or a feature, but on Mac OS X potfit does not read in information in potential files after the last end of line. This means if you do not end the final line of a potential with a line end (whatever characters this may be), this final line will not be read in. If that line contains essential information, potfit will fail.

Can we either read in this information or include in the specification that all lines must be terminated properly?

**Comment by dschopf** [comment]
Commenting out potential_input_f0.c:846+847 should fix this issue. I don't remember why I put this there. Worst case is now we have a crash with some other exotic potential file.

Does this also happen for tabulated potentials?
