### ISSUE TITLE
Memory leak in bracket and brent

### ISSUE THREAD

**Issue by p-bro** [potfit/potfit#35]
_potfit_ is slowly leaking memory (well, not truly leaking - see below) in the brent and bracket routines in Powell minimisation.

The global parameter struct has a sub-structure;
```C
struct {
    double* vecu_bracket;
    double* vecu_brent;
    double* f_vec3;
  } linmin;
```

The brent and bracket routines both then define dynamic variable arrays, set them to the corresponding globals in the definition and, if they are `NULL`, allocate memory for them:

```C
  double* vecu = g_calc.linmin.vecu_bracket;
  double* f_vec3 = g_calc.linmin.f_vec3;
  if (vecu == NULL)
    vecu = (double*)Malloc(g_calc.ndimtot * sizeof(double));
  if (f_vec3 == NULL)
    f_vec3 = (double*)Malloc(g_calc.mdim * sizeof(double));
``` 

This however never updates the global variable, which still points to `NULL` after all this. In consequece, at each passage through these routines, another `2*(ndimtot+mdim)` doubles become allocated. This is not caught by valgrind's leak checker, as the pointer is correctly archived in potfit's memory allocation structure (and will duly be deallocated, if the program finishes).

To solve this, I see in principle two pathways: 

1.  Remove the global variables, and define the respective variables as `static double*` (cf. vecu in linmin.c).
2. Get the global variables updated so that they actually store the pointer to the proper array.

As the variables `vecu_brent`, `vecu_bracket` and `f_vec3` are not used outside the respective arrays, I'd be in favour of solution 1.

**Comment by dschopf** [comment]
Ok, in order to keep the code clean and readable solution 1 seems to be the best option.
