### ISSUE TITLE
Pointless code in setting mindist start values

### ISSUE THREAD

**Issue by p-bro** [potfit/potfit#37]
The following section from config.c seems a bit pointless:
```C
  // set maximum cutoff distance as starting value for mindist
  for (int i = 0; i < g_param.ntypes * g_param.ntypes; i++)
    mindist[i] = DBL_MAX;

  for (int i = 0; i < g_param.ntypes; i++) {
    for (int j = 0; j < g_param.ntypes; j++) {
      int k = (i <= j) ? i * g_param.ntypes + j - ((i * (i + 1)) / 2)
                       : j * g_param.ntypes + i - ((j * (j + 1)) / 2);
      mindist[k] = MAX(g_config.rcut[i * g_param.ntypes + j],
                       mindist[i * g_param.ntypes + j]);
    }
  }
```
`mindist` is first initialised to `DBL_MAX`, then set to the `MAX` of `DBL_MAX` or another value, which will always be `DBL_MAX`. It probably should be set to `MIN`, but I'm not 100% sure if that's desired.

**Comment by dschopf** [comment]
Looks pretty useless to me. I will write some tests and see if removing the code does any harm.

**Comment by dschopf** [comment]
Tests did not show any issues after removing the code.
