### ISSUE TITLE
for help

### ISSUE THREAD

**Issue by mana200256352** [potfit/potfit#39]
hello, everyone .
I am learning potfit now. However, I am wondering that how to treat coulomb+pair potential (for example, coulomb+buck). On www.potfit.net web, it said that "coulomb can not be used together with other force-field approaches ", Therefore, "make potfit_apot_coulomb_pair" was wrong.  it also said that "alternative a buckingham-potential can be used by compiling option buck". However, no option buck was found in potfit options. Also, I have tried "make potfit_apot_coulomb, make potfit_apot_coulomb_buck" using potfit-0.7.1, potfit-20180105 and potfit-20180122. They all give error information like this :
Starting to read the potential file:
 - Potential file format 0 detected: analytic potentials
 - Using 10 ELSTAT potentials to calculate forces
[ERROR] Wrong potential type found in potential file!
[ERROR] This binary only supports ELSTAT potentials.
[ERROR] Your potential file contains a PAIR potential.
So, how to compile the target binary file to solve this question?  Any help are highly appreciated.

**Comment by p-bro** [comment]
A couple of comments:

- Please only file bugs against one of the head revisions on github. Chances are bugs in earlier versions have already been fixed.
- This seems to be more a user question than a bug report. I think the mailing list may be more appropriate to discuss this.
- There was a bug in the documentation - the Buckingham potential does no longer need buck as an option. It also was not clear on what can be combined with what. This is now corrected.
- Your problem can be solved by compiling `make potfit_apot_coulomb`. Your potential file needs to be formatted akin to the example given in [https://www.potfit.net/wiki/lib/exe/fetch.php?media=coulomb_startpot.txt](url) - replacing the ms pair potentials with your preferred pair potential as required.
