### ISSUE TITLE
ACML is outdated and no longer supported

### ISSUE THREAD

**Issue by dschopf** [potfit/potfit#43]
AMD decided to deprecate ACML several years ago. So far we have been supporting this but now GCC has new fortran libraries and I no longer can link ACML without significant efforts.

My plan would be to remove ACML support from potfit master and try to replace it with https://github.com/flame/libflame. Unfortunatley this is not straightforward and requires some work.

@p-bro what do you think?

**Comment by p-bro** [comment]
I would recommend removing ACML support from potfit for the time being. 

From a cursory glance it appears that there is no direct solver for linear equation systems for symmetrical matrices (dsysvx in LAPACK), so one would need to rewrite the operation in terms of operations that are present.

The other use of ACML is for pow, and that seems not present either.

So I'm not fully convinced about the benefits of adding libflame support at this instance.

**Comment by dschopf** [comment]
OK, I will start removing ACML support once I'm back from the KIM sprint.

I thought I saw a custom dsysvx_ implementation in the libflame code but I may be wrong.

Basically I was looking for some open source easy to use replacement for ACML.
