### ISSUE TITLE
when I run './waf configure -i pair -m apot' on terminal in Mac there is a error

### ISSUE THREAD

**Issue by heatwind** [potfit/potfit#50]
Setting top to                           : /Users/qjh/Desktop/makefile test/potfit 
Setting out to                           : /Users/qjh/Desktop/makefile test/potfit/build 
Checking for 'icc' (C compiler)          : not found 
Checking for 'clang' (C compiler)        : /usr/bin/clang 
Checking for header mkl_vml.h            : not found 

After that I install intel c++ compiler and intel Mkl, and copy 'icc' file to /usr/local/bin , but this error still remain.

Somethings are shown on the config.log 

Checking for 'icc' (C compiler)
find program=['icc', 'ICL'] paths=['/usr/local/bin', '/usr/bin', '/bin', '/usr/sbin', '/sbin', '/opt/X11/bin'] var='CC' -> ['/usr/local/bin/icc']
['/usr/local/bin/icc', '-dM', '-E', '-']
err: mcpcom: No such file or directory

I am a new to potfit and something like that.

**Comment by dschopf** [comment]
> After that I install intel c++ compiler and intel Mkl, and copy 'icc' file to /usr/local/bin , but this error still remain.
I am no expert for MacOS, but I don't think that's the correct way to install ICC.

Here is the official documentation from Intel about how to set it up correctly:
https://software.intel.com/en-us/get-started-with-cpp-compiler-19.0-for-macos-parallel-studio-xe-2019

**Comment by heatwind** [comment]
thanks dschopf very much 
I have done it in linux. I think the compile in Macos is hard :)
