### ISSUE TITLE
How to run an example

### ISSUE THREAD

**Issue by heatwind** [potfit/potfit#51]
I have compiled the potfit in linux. And then I want to run a potfit file, as the wiki said [https://www.potfit.net/wiki/doku.php?id=running:main]. 

but I don't know how how to use [potfit_binary <parameter_file>]

The name of the potfit binary depends on the selected potential model and interaction.  So is it potfit_apot_pair <parameter_file> or something else. I have tried many 'commands' and run on the terminal, but it is always said no command found...

**Comment by p-bro** [comment]
You will need to place the potfit binary where your shell can find it. The build process should place the binary in a `bin` subdirectory. You can either copy the binary to wherever you want, or you can call potfit with the full path to the binary. Note that if your current working directory is not in the path, then you'll need to run potfit as `./[potfit_binary] <parameter_file>`.

If this doesn't help, please do provide more information about operating system, shell command and error message.

**Comment by heatwind** [comment]
Thank you p-bro. I have done it!
