### ISSUE TITLE
No atoms found in interaction range for potential 2!

### ISSUE THREAD

**Issue by heatwind** [potfit/potfit#52]
I have run cp2k to obtain energy of many configurations (about C and He).
And then I put them in PotFit.
An error appeared:
No atoms found in interaction range for potential 2!

what's more, are there more examples that I can find in the Internet?
it's too hard to use potfit without many examples.

Thanks

**Comment by dschopf** [comment]
Sorry, cp2k is not officially supported by potfit. From the error message I would assume something with the distance unit conversion is not working properly.

**Comment by heatwind** [comment]
> Sorry, cp2k is not officially supported by potfit. From the error message I would assume something with the distance unit conversion is not working properly.

Thanks, dschopf. 
I know that cp2k is not supported  by potfit. But I wrote a shell file to read the energy and XYZ from CP2K's output file and input file, meanwhile using the shell file writing these into my config file of potfit. I think it's pretty useful.

For the error, I have done. And you're right something wrong of the distance. Thank you!
