### ISSUE TITLE
Can I just calculate only one potential function when there are 2 types of atom?

### ISSUE THREAD

**Issue by heatwind** [potfit/potfit#53]
I want to calculate the lj potential function between A and B, and I don'e need potential functions of A-A and B-B. 

How should I write the pot file?

**Comment by dschopf** [comment]
There are several possibilities, the following should be the rather easy to understand:
```
#F 0 3
#T PAIR
#E
 
type const
cutoff 6.0
c 0 0 0
 
type lj
cutoff 6.0
epsilon 0.10    0.00    1.00
sigma   2.50    1.00    4.00
 
type const
cutoff 6.0
c 0 0 0
```
The potentials between A-A and B-B are constant functions with a value of 0.

If you want to use a specific potential for A-A and B-B look into the #I header line.

**Comment by heatwind** [comment]
> There are several possibilities, the following should be the rather easy to understand:
> 
> ```
> #F 0 3
> #T PAIR
> #E
>  
> type const
> cutoff 6.0
> c 0 0 0
>  
> type lj
> cutoff 6.0
> epsilon 0.10    0.00    1.00
> sigma   2.50    1.00    4.00
>  
> type const
> cutoff 6.0
> c 0 0 0
> ```
> The potentials between A-A and B-B are constant functions with a value of 0.
> 
> If you want to use a specific potential for A-A and B-B look into the #I header line.

Thank you so much!

**Comment by heatwind** [comment]
> There are several possibilities, the following should be the rather easy to understand:
> 
> ```
> #F 0 3
> #T PAIR
> #E
>  
> type const
> cutoff 6.0
> c 0 0 0
>  
> type lj
> cutoff 6.0
> epsilon 0.10    0.00    1.00
> sigma   2.50    1.00    4.00
>  
> type const
> cutoff 6.0
> c 0 0 0
> ```
> The potentials between A-A and B-B are constant functions with a value of 0.
> 
> If you want to use a specific potential for A-A and B-B look into the #I header line.

I find that the results A -B of the case that I calculate all potential functions A-A  A-B B-B and the case that I only calculate one potential function A-B are different.

**Comment by dschopf** [comment]
Well, I am not surprised and probably would have expected this in the first place. Potential fitting is no deterministic process. And if you change some parameters the output may be (vastly) different. 
But without knowing how much these potentials differ and which input data you used there is nothing we can do about it.

**Comment by heatwind** [comment]
> Well, I am not surprised and probably would have expected this in the first place. Potential fitting is no deterministic process. And if you change some parameters the output may be (vastly) different.
> But without knowing how much these potentials differ and which input data you used there is nothing we can do about it.

Thank you very much. I successfully run it.

**Comment by heatwind** [comment]
> Well, I am not surprised and probably would have expected this in the first place. Potential fitting is no deterministic process. And if you change some parameters the output may be (vastly) different.
> But without knowing how much these potentials differ and which input data you used there is nothing we can do about it.

I want to get lj parameters of A atom and B atom in a kind of configuration, and these configurations consist of only A atoms and B atoms. Firstly, I using CP2K got the energy of A atoms and B atoms separately. Then I got total energy of all.
I  let "#E = [energy(total) - energy(only A atoms) - energy(only B atoms)]/ number of atoms"
In potential file. I make A-A potential function and B-B potential function "type const; c 0 0 0" and make A-B potential function type lj.

Is that right?

**Comment by dschopf** [comment]
Honestly I cannot say for sure if that is right or not. For plain pair potentials it seems correct. However, your use case seems rather strange and unusual to me. How would you even use such a potential in a real simulation? There must be some interaction present for A-A and B-B, where does it come from? Why can't you use this interaction already in the fitting process?
