### ISSUE TITLE
How to run a tabulated potential

### ISSUE THREAD

**Issue by heatwind** [potfit/potfit#54]
I want to run a tabulated potential.
these are my potfit_binary, potential file and errors:

- 
potfit_tab_pair_mkl

- 
#F 3 3
#T PAIR
#E

1.3 5 120

1.3 5 120

1.3 5 120

- 
Error: 
[ERROR] Premature end of potential file lj.pot

The example in manual just give #F and #E.
What should I add to my potential file?

**Comment by dschopf** [comment]
I don't see how this could be a valid potential file. It looks like you are missing the function tables.
The distance block indicates that there are 3 function tables, each with 120 entries. So your file needs to have about 370 lines in total and not just 10.
There is a description for the format available [here](https://www.potfit.net/wiki/doku.php?id=potfiles:format3).

And you can also download an example potential file [here](https://www.potfit.net/wiki/lib/exe/fetch.php?media=format_3.pot.txt).

PS: 120 entries per potential is way too much and will not result in anything useful. You should start with something like 8 or 10 sampling points.

**Comment by heatwind** [comment]
> I don't see how this could be a valid potential file. It looks like you are missing the function tables.
> The distance block indicates that there are 3 function tables, each with 120 entries. So your file needs to have about 370 lines in total and not just 10.
> There is a description for the format available [here](https://www.potfit.net/wiki/doku.php?id=potfiles:format3).
> 
> And you can also download an example potential file [here](https://www.potfit.net/wiki/lib/exe/fetch.php?media=format_3.pot.txt).
> 
> PS: 120 entries per potential is way too much and will not result in anything useful. You should start with something like 8 or 10 sampling points.

Thank you so much. I successfully run it!
