### ISSUE TITLE
What does the error report mean?

### ISSUE THREAD

**Issue by heatwind** [potfit/potfit#55]
I am a greenhorn of potfit. I don't know some parameters in error report represent, and hoping to get help.

1. "total error sum A, count B. "
A: What does it mean?
B: In my opinion, if the energy from configuration file is different to the energy calculated by the potential function which we got using potfit, then the count of error will plus 1. 

2. "rms-errors: 
     force  C  (C meV/A)
     energy D  (D meV)"
C and D: What does rms-errors mean?

Thank you for your patience!

**Comment by dschopf** [comment]
Ok, I see we need more documentation for the error report. I will start adding some more details if I find some time.

1. A is the total error sum calculated from all deviations from the reference data. In a very simple configuration with 1 energy value and 2 atoms this would probably the sum of E-E_0 and the difference of all 6 force components from their reference value. The count B gives you the total amount of values which contribute to the sum A. There is also the number of force and energy contributions.

2. rms stands for [root-mean-square](https://en.wikipedia.org/wiki/Root-mean-square_deviation) and should give you a rough idea how good or bad the force, energy and stress values for the final potential are. For a potential which can reproduce the reference values exactly these values will all be zero. 

Meanwhile I have changed the error output slightly to make it more clear what the numbers actually mean (98b2119 ).

**Comment by heatwind** [comment]
> Ok, I see we need more documentation for the error report. I will start adding some more details if I find some time.
> 
> 1. A is the total error sum calculated from all deviations from the reference data. In a very simple configuration with 1 energy value and 2 atoms this would probably the sum of E-E_0 and the difference of all 6 force components from their reference value. The count B gives you the total amount of values which contribute to the sum A. There is also the number of force and energy contributions.
> 2. rms stands for [root-mean-square](https://en.wikipedia.org/wiki/Root-mean-square_deviation) and should give you a rough idea how good or bad the force, energy and stress values for the final potential are. For a potential which can reproduce the reference values exactly these values will all be zero.
> 
> Meanwhile I have changed the error output slightly to make it more clear what the numbers actually mean ([98b2119](https://github.com/potfit/potfit/commit/98b21191426dc2be2f8bde6963989fd7dfaf2900) ).

Thank you very much! I get it.
