### ISSUE TITLE
How potfit figure out lj potential function of A-A when there is only one A atom in configurations.

### ISSUE THREAD

**Issue by heatwind** [potfit/potfit#56]
How potfit figures out lj potential function of B-B when there is only one A atom in configurations？

I want to figure out A-B lj potential with the configuration consisting of many A atoms and only one B atom. In potential file, I make all potential functions (A-A A-B B-B) lj potential function. I run it, and in surprise found potfit also give me the lj parameters of B-B.

Why is that?
Thanks for your help!

**Comment by p-bro** [comment]
B-B atoms might interact across periodic boundaries (i.e. with a copy of itself). Note however that the B-B interaction produced is most likely not useful.

The way pair potentials work in potfit, all pairs of atom types must have a potential. If you do not want a pair to interact you have to set the B-B interaction to zero and prevent optimisation. If you do not tell potfit **not** to optimise a pair potential, it will optimise them. If there is truly no pair B-B available, it might throw an error, as the target function (error sum) does not depend on the parameters of that potential.

**Comment by heatwind** [comment]
> B-B atoms might interact across periodic boundaries (i.e. with a copy of itself). Note however that the B-B interaction produced is most likely not useful.
> 
> The way pair potentials work in potfit, all pairs of atom types must have a potential. If you do not want a pair to interact you have to set the B-B interaction to zero and prevent optimisation. If you do not tell potfit **not** to optimise a pair potential, it will optimise them. If there is truly no pair B-B available, it might throw an error, as the target function (error sum) does not depend on the parameters of that potential.

Thank you so much!
