### ISSUE TITLE
is the SUM OF ENERGY-ERRORS from error reports a sum of absolute values?

### ISSUE THREAD

**Issue by heatwind** [potfit/potfit#57]
I fitting lj potential parameters using potfit, find the results were bad, but the error reports said that the error is very small. 

So, is the sum of energy-errors from error reports a sum of absolute values? or not? Because, if there are two errors -1 and 1, while the sum of errors is ZERO!

Thanks for your read!

**Comment by p-bro** [comment]
Unfortunately the information you provide is insufficient to say anything. Can you share at least some of the error report?

**Comment by heatwind** [comment]
> Unfortunately the information you provide is insufficient to say anything. Can you share at least some of the error report?

SORRY, there is a mistake in my potfit files.  :)
