### ISSUE TITLE
not found of MPI while I have installed MPI

### ISSUE THREAD

**Issue by heatwind** [potfit/potfit#59]
----------------------------------------
Checking MPI compiler command
['mpicc', '--showme:compile']
err: gcc: error: unrecognized command line option ‘--showme:compile’; did you mean ‘--compile’?

not found

I run 'which MPI' and get respond.

**Comment by heatwind** [comment]
this happened when I run './waf configure -i pair -m apot --enable-mpi'
when I run './waf configure -i pair -m apot', it's done

**Comment by dschopf** [comment]
Which MPI implementation are you using and which version?
