### ISSUE TITLE
what's the mean of the index F in simulated annealing

### ISSUE THREAD

**Issue by QianJianhao** [potfit/potfit#62]
I using POTFIT fit LJ parameters via simulated annealing. There are some index (k, T, m, F, F_opt) I  don't understand. I know that T is the annealing temperature. 

1.What's index m? when run opt with 2 parameters, m is from 1 to 6. when 4 parameters, m is from 1 to 12. I am curious about the mechanism.
2.How POTFIT calculate F?
3.The difference of F with different m?
4.How POTFIT calculate F_opt?

Thank you very much!

![Snipaste_2019-08-24_16-05-28](https://user-images.githubusercontent.com/54468140/63634579-077e9200-c68b-11e9-90bd-72e2a05ca9b5.png)

**Comment by dschopf** [comment]
1. The index m runs from 0 to 3*(number of parameters). 
2. F is the total error sum, described [here](https://www.potfit.net/wiki/doku.php?id=algorithms:main) as Z(\xi)
3. After each m loop the most recent value of the error function F is printed
4. F_opt is the current optimal configuration which has been found so far

If you want to know more about the algorithm please read up on the cited publications on the potfit homepage.
