### ISSUE TITLE
potential can not be used for lammps

### ISSUE THREAD

**Issue by wangnumber14** [potfit/potfit#65]
hello, 
I have made a test, use TiO2 containing 12 atoms as initial configuration to get a lj or eam potential.

TiO2.conf is as  follows, it was generated by vasp2force:
`#N 12 1
#C O Ti
## force file generated from file /out/1/OUTCAR_TiO2 config 1
#X    3.83098745    0.00000000    0.00000000
#Y    0.00000000    3.83098745    0.00000000
#Z    0.00000000    0.00000000    9.61914623
#W 1.000000
#E -8.8315350950
#S -0.001346292 -0.001346292 0.002171261        0        0        0
#F
0           0           0      2.0007           0           0   -0.026121
0     1.91549     1.91549     6.81027           0          -0   -0.026121
0           0     1.91549     4.40549          -0          -0   -0.026121
0     1.91549           0     9.21506          -0          -0   -0.026121
0     1.91549           0     5.21366           0           0    0.026121
0           0     1.91549     0.40409          -0           0    0.026121
0     1.91549     1.91549     2.80887           0           0    0.026121
0           0           0     7.61845           0          -0    0.026121
1           0           0           0           0          -0           0
1     1.91549     1.91549     4.80957           0          -0           0
1           0     1.91549     2.40479          -0          -0           0
1     1.91549           0     7.21436          -0          -0           0`
the pot file is generated by makeapot command:
makeapot -n 2 -i eam -g -f 3*morse_sc 2*csw2_sc 2*bjs

the param file is :
`ntypes          2
config          TiO2.config
startpot        TiO2_eam.pot
endpot          TiO2_eam.pot_end
tempfile        TiO2_eam.tmp

imdpot          TiO2_eam.imd
plotfile        TiO2_eam.plot
flagfile        STOP

write_pair      1
write_lammps    1
plotmin         0.1
enable_cp       0

imdpotsteps     5000
output_prefix   TiO2_eam

opt             1
anneal_temp     auto
eng_weight      100
stress_weight   10
seed            42
apot_punish     0`

It had generated a potential file named TiO2_eam.lammps.EAM,

when I use this potential in lammps,  I had a message from lammps "ERROR: Invalid EAM potential file (../pair_eam.cpp:487)"

the potential is in the attachment.
[TiO2_eam.lammps.zip](https://github.com/potfit/potfit/files/4192230/TiO2_eam.lammps.zip)

Can you give me an example which can work for lammps? Thank you very much.

**Comment by dschopf** [comment]
Which LAMMPS pair_style are you using? The generated potential file requires the use of "pair_style eam/alloy". The plain "pair_style eam" is not supported.

If you are already using "eam/alloy", can you please provide the version of LAMMPS you are using and the input file as well?

**Comment by wangnumber14** [comment]
Yes，I have used plain "pair_style eam", I have changed the parameter "pair_style", and it works.
More question, which interaction generated by potfit cannot be used for lammps? is there some instruction？ Can you give me some links about this?

Thanks a lot.

**Comment by dschopf** [comment]
Yes, you can find some details here: https://www.potfit.net/wiki/doku.php?id=output:lammps

**Comment by hidayatullahkhan** [comment]
Dear
I am facing a problem while using potfit to optimize stillinger weber potential for 2d system to generate its lammps potential file for further lammps applications . I used write_lammps in parameter file to generate lammps file after optimization. but after optimization i get the following  warring massage at the end  
[WARNING] Your potential is not supported by LAMMPS.
[WARNING] Please ensure that the values a1 and a2 are the same,
[WARNING]   either by using global parameters or by fixing them.

**Comment by dschopf** [comment]
All you need to know about this warning is described here: https://www.potfit.net/wiki/doku.php?id=potfiles:format0
In case you have any additional questions please open a new issue.
