### ISSUE TITLE
Compilation of potfit with the Netlib LAPACK library?

### ISSUE THREAD

**Issue by anneb101** [potfit/potfit#66]
Hello potfit community,

I am new to the software, and after some searching it appears that potfit requires the Intel MKL library for LAPACK. Based on an earlier Github thread, it appears that the ACML library is no longer supported (https://github.com/potfit/potfit/issues/43). 

If we don't have access to MKL, is it possible to compile with the library available from Netlib?

Thank you,
Anne

**Comment by dschopf** [comment]
So far potfit does not (yet) support the Netlib LAPACK package. I will first have to take a look before making any promises. If I don't post any update within one week, please remind me to do so.

**Comment by anneb101** [comment]
Hi, thank you for your reply earlier. I was just checking in on this issue.
Thank you,
Anne

**Comment by dschopf** [comment]
So from an initial assessment I don't see any reason why we could not support that implementation. I hope to find some time on the weekend to try to integrate it. Should not be too complicated.

**Comment by anneb101** [comment]
Great to hear; thank you!

**Comment by dschopf** [comment]
If you are able I would like to ask you to test the changes provided in #67. Compiling works, I did not yet perform any tests so far.

**Comment by anneb101** [comment]
Hello, I just tried compiling, based on the instructions on this page: https://www.potfit.net/wiki/doku.php?id=compiling:main

I used the default line:
`./waf configure -i pair -m apot`

Resulting in:

```
Setting top to                           : /home/anne/Downloads/potfit-lapack-support 
Setting out to                           : /home/anne/Downloads/potfit-lapack-support/build 
Checking for 'gcc' (C compiler)          : /usr/bin/gcc 
Checking for header mkl_vml.h            : not found 
The configuration failed
(complete log in /home/anne/Downloads/potfit-lapack-support/build/config.log)
```

Relevant section from config.log:


```
----------------------------------------
Checking for header mkl_vml.h
==>
#include <mkl_vml.h>

int main(int argc, char **argv) {
	(void)argc; (void)argv;
	return 0;
}

<==
[1/2] Compiling [32mbuild/.conf_check_0c537d49534051e465708e3b927fd9b1/test.c[0m

['/usr/bin/gcc', '-O3', '-march=native', '-std=c99', '-I/opt/intel/mkl/include', '-DNDEBUG', '../test.c', '-c', '-o/home/anne/Downloads/potfit-lapack-support/build/.conf_check_0c537d49534051e465708e3b927fd9b1/testbuild/test.c.1.o']
err: ../test.c:1:10: fatal error: mkl_vml.h: No such file or directory
 #include <mkl_vml.h>
          ^~~~~~~~~~~
compilation terminated.

from /home/anne/Downloads/potfit-lapack-support: Test does not build: Traceback (most recent call last):
  File "/home/anne/Downloads/potfit-lapack-support/.waf-2.0.19-8538b4ab53a7d24a478b70cb8d72b921/waflib/Configure.py", line 333, in run_build
    bld.compile()
  File "/home/anne/Downloads/potfit-lapack-support/.waf-2.0.19-8538b4ab53a7d24a478b70cb8d72b921/waflib/Build.py", line 176, in compile
    raise Errors.BuildError(self.producer.error)
BuildError: Build failed
 -> task in 'testprog' failed with exit status 1 (run with -v to display more information)

not found
from /home/anne/Downloads/potfit-lapack-support: The configuration failed
```

**Comment by anneb101** [comment]
Also, after doing a quick grep for "mkl" in the potfit folder, I saw some more headers present that include mkl. 

```
src/utils.c:#include <mkl_vml.h>
src/powell_lsq.c:#include <mkl_lapack.h>
src/uq.c:#include <mkl_lapack.h>
```

**Comment by dschopf** [comment]
I'm sorry, I should have provided more context here. My changes in #67 require you to explicitly select LAPACK by providing the `-l lapack` or `--math-lib=lapack` command line arguments.

I will try to add an autodetect feature which makes this command line switch optional.

> Also, after doing a quick grep for "mkl" in the potfit folder, I saw some more headers present that include mkl.

Yes, that is expected and should not be an issue.

**Comment by anneb101** [comment]
Ok, thank you. I added the flag, and I am now seeing the following message. Is there something I need to do to link the lapack libraries properly in the Makefile?

```
 ./waf configure -i pair -m apot -l lapack
Setting top to                           : /home/anne/Downloads/potfit-lapack-support 
Setting out to                           : /home/anne/Downloads/potfit-lapack-support/build 
Checking for 'gcc' (C compiler)          : /usr/bin/gcc 
Checking for program 'pkg-config'        : /usr/bin/pkg-config 
Checking for 'lapack'                    : yes 
Checking for header lapack.h             : not found 
```

**Comment by dschopf** [comment]
It looks like your system configuration is not working as expected by potfit. Could you attach the complete configuration log generated by the `waf configure` step?

**Comment by anneb101** [comment]
[config.log](https://github.com/potfit/potfit/files/4645195/config.log)

**Comment by dschopf** [comment]
Hmm, this is strange. According to `pkg-config` there should be no special include path for the LAPACK headers, but it cannot be found in the default include paths.

Which distribution are you using and which LAPACK package did you install exactly?

**Comment by anneb101** [comment]
I installed it using "sudo apt-get install liblapack" in Ubuntu.

However, I have had prior experience compiling it from scratch. If that is critical for the potfit built, please let me know if I need to have it present in a certain directory or linked in a certain way.

Thank you,
Anne

**Comment by dschopf** [comment]
For Ubuntu you usually also need the *-dev package, which provides the header files.

Can you try to run `sudo apt install liblapacke-dev` and then try to build potfit afterwards?

**Comment by anneb101** [comment]
Just did so. Still getting the same error (lapack.h not found).

**Comment by dschopf** [comment]
It looks like older versions of Ubuntu did not ship the lapack.h header file at all but only the lapacke.h one.

I will have to make some adjustments to make this work. I will let you know once this is done.

**Comment by anneb101** [comment]
Ok, thank you very much for your assistance.

**Comment by dschopf** [comment]
I pushed a new commit which hopefully fixes your issues. It is now no longer necessary to provide the `-l lapack` option. potfit will now look for MKL headers and use LAPACK in case they cannot be found.

**Comment by anneb101** [comment]
Compiles successfully now! Thank you very much.

**Comment by dschopf** [comment]
Great, once the PR is reviewed this will become available in the regular release.

**Comment by Anmol-Bakshi** [comment]
> I pushed a new commit which hopefully fixes your issues. It is now no longer necessary to provide the `-l lapack` option. potfit will now look for MKL headers and use LAPACK in case they cannot be found.

I am also facing the same issue of lapack not found. Can you help in fixing it ?
[config.log](https://github.com/potfit/potfit/files/9032895/config.log)

**Comment by dschopf** [comment]
Please don't reuse already closed issues, just create a new one. And please also provide some details about you system setup like operating system and the version of LAPACK you have installed.
