### ISSUE TITLE
error while adding new potential function

### ISSUE THREAD

**Issue by wjinjin** [potfit/potfit#68]
Hi,  I'm using potfit to fit a new potential and I have added a new potential function as the guide on the website: https://www.potfit.net/wiki/doku.php?id=models:adding_analytic_functions. 
And it shows an error while I use ./waf build: 
In file included from ../src/functions.h(42),                  
                        from ../src/mpi_utils.c(33): 
../src/functions.itm(84): error: extra text after expected end of number  
FUNCTION(jinjin_3.2, 3);  
What should I do to solve this problem? Thanks!

**Comment by dschopf** [comment]
Your function name must be a valid C identifier, i.e. dots are not allowed.
Try to change `FUNTION(jinjin_3.2, 3);` to `FUNCTION(jinjin_3_2, 3);`, that should work.
