### ISSUE TITLE
[ERROR] Premature end of potential file pot_start.txt

### ISSUE THREAD

**Issue by krishnansiddharth** [potfit/potfit#74]
Hi POTFIT community,

I am trying to generate a tabulated EAM potential for a single element using profit. I have attached my starting potential and parameter file. Running potfit with the binary potfit_tab_eam_mkl is resulting in an error(the title of the post).  I am unable to find the error. 

Any help will be highly appreciated.

[pot_start.txt](https://github.com/potfit/potfit/files/5363149/pot_start.txt)
[param.txt](https://github.com/potfit/potfit/files/5363151/param.txt)

Thanks and Regards,
Siddharth

**Comment by p-bro** [comment]
Your potential file uses the `#G` header line. This requires specifying the gradients at the boundaries at the start of each function block (or 1e30, if you want natural splines). Unfortunately, this information was missing from the format4 page of the wiki, where I have inserted it now.

So your potential file needs three more lines, one at the start of each block.

**Comment by krishnansiddharth** [comment]
Hi, 

Thanks for the prompt reply. I did as you have said, and yet face the error. I have added my potential file let me know if there are any further corrections I need to make.

Thanks and Regards
[pot_start.txt](https://github.com/potfit/potfit/files/5364813/pot_start.txt)
,
Siddharth

**Comment by p-bro** [comment]
Your file uses − (U+2212 : MINUS SIGN) instead of - (U+002D : HYPHEN-MINUS) as a minus sign. While this is typographically correct, potfit apparently has problems reading UTF and correctly interpreting non-standard characters. If you replace all − with -, your file reads fine.

@dschopf - is that something we need to fix?

**Comment by krishnansiddharth** [comment]
Hi, 

I changed the minus signs in the file as well. The error persists. 

Thanks and Regards,
Siddharth
[pot_start.txt](https://github.com/potfit/potfit/files/5366112/pot_start.txt)

**Comment by dschopf** [comment]
The data you have provided works for me without any errors. Could you please provide the version of potfit you are using as well as the complete output you receive when you run it?

@p-bro I don't think we need to fix this, this would probably impossible to get right. We should ask people to provide sane files. Only thing we might consider is to check for non-ASCII characters (>0x80) and print a warning.

**Comment by krishnansiddharth** [comment]
Hi, 

I am using **potfit-20200729.** The error message I receive is as follows
This is potfit-20200729 (2a72c47a) compiled on Oct 12 2020, 10:14:26.

Reading parameter file >> param.txt << ...
[WARNING] Unknown tag <stress_weight> in parameter file ignored!
[WARNING] Unknown tag <evo_threshold> in parameter file ignored!
[WARNING] endpot is missing in param.txt, setting it to pot_start.txt_end
Reading parameter file >> param.txt << ... done
Starting to read the potential file:
 - Potential file format 4 detected: tabulated non-eqdist
 - Using 3 EAM potential(s) to calculate forces
[ERROR] Premature end of potential file pot_start.txt

**Comment by p-bro** [comment]
This file works for me.
[pot_start.txt](https://github.com/potfit/potfit/files/5370203/pot_start.txt)

@dschopf - I've added more specific information to the "Premature end of potential file" error message. It's not particularly helpful to find a bug, if the same error message appears in multiple locations.

**Comment by krishnansiddharth** [comment]
Is it possible that the error is in the parameter file? Are you running the potential file through the parameter file I had provided and the binary potfit_tab_eam_mkl?

 I ran the file using the potfit-git as well. The error persists.

I hope there is no issue with the way I have configured potfit. I followed the instructions on [https://www.potfit.net/wiki/doku.php?id=compiling:main](url)

Thanks and Regards,
Siddharth

**Comment by p-bro** [comment]
The error is most certainly in the potential file, probably a character encoding issue (the only change I made to your parameter file was changing the name of the config file. 

The potential file I provided above was encoded as ASCII file and worked without issue for me on the current potfit as on github. The file you provided above was encoded as UTF-8 and did not work. Perhaps your OS is doing something funny to files when saving them. 

If you want, you can check out potfit from my fork at https://github.com/p-bro/potfit where I committed an update that gives you more information about _where_ a file finds its premature end.

**Comment by krishnansiddharth** [comment]
Hi,

Thank you very much for your help and your prompt replies. 

It seems the format in which the file was the issue. I used the version of the potential file you provided me with and the simulation works now. 

Thanks and Regards,
Siddharth
