### ISSUE TITLE
Analytic form for EAM potential

### ISSUE THREAD

**Issue by krishnansiddharth** [potfit/potfit#78]
Hi potfit community,

I was trying to generate an analytic EAM potential using potfit, but could not find any information on the functional form of the electron density and embedding function in the documentation. Can you please direct me as to where I can find the details  about these functions?

Thanks  and Regards,
Siddharth.

**Comment by dschopf** [comment]
If you check the [Analytic potential functions](https://www.potfit.net/wiki/doku.php?id=models:analytic_functions) page on the potfit wiki you can find some functions and their reference which have been used for analytic EAM potentials.
In case you want to use another functional form you can add your own function using [this guide](https://www.potfit.net/wiki/doku.php?id=models:adding_analytic_functions).

**Comment by krishnansiddharth** [comment]
Thank you very much. This was extremely helpful.
