### ISSUE TITLE
Confusion in the selection of stillinger weber potential file 

### ISSUE THREAD

**Issue by hidayatullahkhan** [potfit/potfit#80]
Dear!
I want to optimize stillinger weber potential for 2D structure so for that, I am quite confused about the selection of SW potential parameters. actually, I generate SW potential file by "makeapot" command  which set all the parameters within the cutoff range but when I get the optimized parameters SW potential and then used it for real simulation it gives the following error "illegal potential parameters"

**Comment by dschopf** [comment]
Sorry, but without any additional information you won't get any help. What is a real simulation and who gives an error?

**Comment by hidayatullahkhan** [comment]
Actually, I want to optimize Stillinger weber(SW) parameters to do the classical molecular dynamics (CMD) for ZnS thin film. basically, I am not sure about that how can select the parameters of SW potential. I just generate  SW potential file using the "makeapot" command. am I doing right? so please guide me in this regard. Thanks

**Comment by dschopf** [comment]
This issue should be fixed with c05c7c05b479f53c794cb9aa33cfcfd6cc55d1f8. A new release is currently blocked by some other isues, please apply these changes manually to your checkout.

**Comment by weileiweilei** [comment]
> Actually, I want to optimize Stillinger weber(SW) parameters to do the classical molecular dynamics (CMD) for ZnS thin film. basically, I am not sure about that how can select the parameters of SW potential. I just generate SW potential file using the "makeapot" command. am I doing right? so please guide me in this regard. Thanks

Hello ghost:
Did you solve your issue ? I'm encountering the similar issue, Thank you !
