### ISSUE TITLE
Releases on github

### ISSUE THREAD

**Issue by akesandgren** [potfit/potfit#81]
Hi!

It would be beneficial to keep actual releases available from github instead of only from your web download.

**Comment by dschopf** [comment]
Since we don't have official releases and simply package the sources into an archive, I don't see any benefit in this. You can simply clone the git repo and check out the commit from that day to get the "release code".

Do you have a workflow or use case which cannot be covered by this?

**Comment by akesandgren** [comment]
From a HPC site installation, and from a reproducability of results, point of view, an actual release is MUCH preferred.
Scientists do expect to be able to reproduce their data, and the only way to properly do that is to know which version of each software was used in the first place. Thus one need official versioned releases.

This can be as simple as adding a tag, preferably an annotated tag, an pushing it to github.
A good version scheme used by many projects is simply the date in the yyyymmdd format.
It should preferably be a stable version without too many known bugs :-)

**Comment by dschopf** [comment]
We already have (most of) this. I will try to see if there is an easy way to upload a release also to github.

**Comment by dschopf** [comment]
Ok, I have checked and we already have a folder to download old releases. Only the link was missing from the download page.

Please check here https://www.potfit.net/wiki/doku.php?id=download. Links are somehow displayed strangely at the moment, but they are working.

**Comment by arielzn** [comment]
@dschopf is there a reason for not tagging also the repo here each time you make a new release ?

as it was done in the past up to v0.7.1  

that would be useful to get a nice way to compare versions, on a local clone with `git diff` or here on github as:

https://github.com/potfit/potfit/compare/0.7.0...0.7.1

to spot fast which changes were made to the source between releases.

**Comment by dschopf** [comment]
Not a particular one, I just don't see the point in tagging every commit (we immediately release each commit which passes all tests as a new release).

But if you say that you need this or that this would help you in a certain way we can surely do that.

**Comment by akesandgren** [comment]
Tagging every commit is useless, you have the commits themselves for that. But every release and specific bugfix-versions should be tagged.

5 Jul 2021 19:36:52 Daniel Schopf ***@***.***>:

**Comment by arielzn** [comment]
by checking the list of releases on https://www.potfit.net/download/  last 2 releases are 2Jul2021 and 14Oct2020 ,  by looking at commits history https://github.com/potfit/potfit/commits/master  we see 3 commits between these 2 dates.

Even if they are minor fixes or even doc fixes, in general is useful to have something relating the published tarballs and the precise commit from where it was based, like a tag.

Also, by going later in history there are many times a batch of several commits on a single day.

**Comment by dschopf** [comment]
The missing releases can be explained by failing tests, which blocked the release. You can see that here: https://jenkins.potfit.net/job/test_potfit/

The only flaw in the current system is that for multiple (unrelated) commits the last commit from a day will be the release and previous releases from the same day will be discarded. I think the odds of this happening are rather low and to me I don't see why this matters.

But if you want tags for each release/commit then I will do it. But I won't do it for past releases. Btw, this will also have the same issue when there is more than one commit per day.
