### ISSUE TITLE
size of the reference data and number of the reference configuration data file 

### ISSUE THREAD

**Issue by hidayat0139** [potfit/potfit#83]
How many reference configuration data files and how much size of reference data are essential for the accurate optimization of Stillinger weber (sw) potential? 
I have done some runs with five reference configuration data which consist of 8 atoms but do not get the correct potential.

**Comment by dschopf** [comment]
There is no right amount of refence configurations, I recommend reading some of the publications about potfit to get a better understanding of what you need and how you can get there.

I can recommend 
- Chapter 4.1.1 in https://elib.uni-stuttgart.de/handle/11682/4836 
- Chapter 6.4 in https://elib.uni-stuttgart.de/handle/11682/5115

And there is also no "correct potential", there will be a potential which can reproduce certain quantities better or worse than other potentials. But this highly depends on your application and which properties you actually want to simulate. So putting data into potfit and retrieving an establish potential from the literature will most likely never work.
