### ISSUE TITLE
coulomb and born potentials

### ISSUE THREAD

**Issue by hacortesp** [potfit/potfit#88]
Dear Admin,

I am trying to use a combination of Born and Coulomb potentials, is this possible?
It should be equal to use the combination of Buckingham and Coulomb potentials (previously described in this email list) if delta and r0 in Born potential are equal to 0. However, when I ran potfit with 'potfit_apot_coulomb_mkl_stress', I got results quite differents for Born+Coulomb and Buck+Coulomb.

Best regards

Henry Cortes

**Comment by p-bro** [comment]
Hi Henry,
please note that in addition to delta and r0 equal to zero, you also need to scale gamma: The born gamma is equal to the buck gamma times beta^6 - see https://www.potfit.net/wiki/doku.php?id=models:analytic_functions for the definition.
Best, Peter

**Comment by hacortesp** [comment]
Dear Peter 

I forgot to say that "scale gamma" in the previous message, I did that and I got a quite different result.
These are my pot files for born and buck potentials in combination with Coulomb.

[LLZO.pot_born.txt](https://github.com/potfit/potfit/files/7459343/LLZO.pot_born.txt)

[LLZO.pot_buck.txt](https://github.com/potfit/potfit/files/7459347/LLZO.pot_buck.txt)

**Comment by dschopf** [comment]
I guess the root cause of this lies in the fact that for `COULOMB` interactions the `buck` function is implemented differently from running non-electrostatic fits. You can see it here: https://github.com/potfit/potfit/blob/master/src/functions_impl.c#L142

We probably should fix this in the documentation or even rename the functions so that either of them is available with any potfit configuration.

**Comment by dschopf** [comment]
New potfit release which fixes this issue has been released and documentation has been updated as well.

**Comment by weileiweilei** [comment]
@hacortesp Hi hacortesp, It seems that you compiled potfit with coulomb interaction, yet, there is no coulomb function for "makeapot" command when generating potential file. What function did you choose? 
Can it work that compiling potfit with one interaction and generating potential file with another? @p-bro @dschopf 
Thank you!
